clear variables
close all

Fig9_FastRetraction_CDD
X2 = V0_vals*1000;
YMatrix2 = tau_EC;

clearvars -except X2 YMatrix2
Fig9_changing_a_CDD
X1 = a0_vals*1000;
YMatrix1 = tau_EC;

%% function createfigure(X1, YMatrix1, X2, YMatrix2)
%CREATEFIGURE(X1, YMatrix1, X2, YMatrix2)
%  X1:  vector of semilogx x data
%  YMATRIX1:  matrix of semilogx y data
%  X2:  vector of semilogx x data
%  YMATRIX2:  matrix of semilogx y data

%  Auto-generated by MATLAB on 30-Oct-2024 11:29:50

% Create figure
figure1 = figure('OuterPosition',[2093.8 -115 855.2 747.2]);

% Create axes
axes1 = axes;
hold(axes1,'on');

% Create multiple line objects using matrix input to semilogx
semilogx1 = semilogx(X1,YMatrix1);
set(semilogx1(1),'DisplayName','$c_\mathrm{PS16} = 20$ [wppm]');
set(semilogx1(2),'DisplayName','$c_\mathrm{PS16} = 100$ [wppm]');
set(semilogx1(3),'DisplayName','$c_\mathrm{PS16} = 200$ [wppm]');
set(semilogx1(4),'DisplayName','$c_\mathrm{PS16} = 500$ [wppm]');
% set(semilogx1(5),'DisplayName','2000 ppm PS16');
colororder(winter(4))

% Create ylabel
ylabel('$\tau_\mathrm{EC}$ [s]');

% Create xlabel
xlabel('$a_0$ [mm]');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 0.15]);
box(axes1,'off');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XMinorTick','on','XScale','log');
ylim(axes1, [0,0.12])
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','best');

% Create axes
axes2 = axes('Parent',figure1,...
    'Position',[0.131303520456708 0.116788321167884 0.774500475737391 0.807492254371691]);
hold(axes2,'on');
ylim(axes2, [0,0.12])

% Create multiple line objects using matrix input to semilogx
semilogx(X2,YMatrix2,'LineStyle',':');

% Create ylabel
% ylabel('$\lambda$ [s]');

% Create xlabel
xlabel('$V_0$ [mm/s]','VerticalAlignment','top');

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 0.15]);
box(axes2,'off');
hold(axes2,'off');
% Set the remaining axes properties
set(axes2,'Color','none','XAxisLocation','top','XMinorTick','on','XScale',...
    'log','YAxisLocation','right');
% Create arrow
annotation(figure1,'arrow',[0.3639391056137 0.364414843006659],...
    [0.342673965936741 0.251824817518249]);

% Create arrow
annotation(figure1,'arrow',[0.447193149381541 0.447193149381541],...
    [0.427223844282239 0.538929440389294],'LineStyle',':');

annotation('textbox', 'String', "$c_\mathrm{PS7} = 200$ [wppm]")

findfigs
